CREATE TABLE AULA_SEQUENCE (
ID NUMBER,
DESCRICAO VARCHAR2(30))

INSERT INTO AULA_SEQUENCE VALUES (1,'VERGS');

CREATE SEQUENCE MINHA_SEQUENCIA;

SELECT MINHA_SEQUENCIA.NEXTVAL FROM DUAL;

INSERT INTO AULA_SEQUENCE VALUES (SQ_2.NEXTVAL,'TESTE VERGS');

SELECT * FROM AULA_SEQUENCE ORDER BY 1;

CREATE SEQUENCE SQ_3 START WITH 10 INCREMENT BY 5 MAXVALUE 200 CYCLE;

CREATE SEQUENCE DER_ID_SEQ START WITH 100 INCREMENT BY 1;

CREATE TABLE ORDERS (
ORDER_ID NUMBER,
CUSTOMER_NAME VARCHAR2(30),
ORDER_DATE DATE
)

